gtracker/config/routes.rb
Gtracker::Application.routes.draw do
  resources :users, :sessions
  match 'signup/' => 'users#new'
  match 'signin/' => 'sessions#new'
  match 'signout/' => 'sessions#destroy'
  match '/' => 'main#index'

end

gtracker/app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :salt

  validates_presence_of :name, :email
  validates_uniqueness_of :email
  validates :password,  :presence => true,
                        :confirmation => true,
                        :length => { :within => 6..40 } 

  before_save :encrypt_password 

  def has_password?(pass)
    return encrypted_password == encrypt(pass)
  end

  def self.auth(email, pass)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(pass)
  end

  def self.auth_salt(id, salt)
    user = find_by_id(id)
    (user && user.salt == salt) ? user : nil
  end

  private
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

gtracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

gtracker/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

gtracker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if signed_in?
      redirect_to current_user
      flash.now[:error] = "Already signed in"
    end
  end

  def create
    user = User.auth(params[:session][:email], params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password"
      render 'new'
    else
     sign_in user
     redirect_to '/'
    end
  end

  def destroy
    if signed_in?
      sign_out
      redirect_to '/'
    else
      flash.now[:error] = "You are not signed in"
    end
  end
end

gtracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to '/'
    else
      render 'new'
    end
  end
end

gtracker/app/helpers/application_helper.rb
module ApplicationHelper
end

gtracker/app/helpers/main_helper.rb
module MainHelper
end

gtracker/app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in?
    !self.current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.auth_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end
end

gtracker/app/helpers/users_helper.rb
module UsersHelper
end

gtracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gtracker</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="logo_container">
  <div id="logo_header">
      <%= image_tag("gtrack-logo.png", :alt => "logo", :width => "100%") %>
  </div>
</div>

<div id="main">
  <% flash.each do |key, value| %>
    <div class="flash_<%=key%>"><%= value %>"</div>
  <% end %>

    <div id="sidebar">
    <% if !signed_in? %>
      <p> Sign in </p>
    <!-- todo partial --!>
      <%= form_for(:session, :url => sessions_path) do |f| %>
        <div class="field">
          <%= f.label :email %><br/>
          <%= f.text_field :email %>
        </div>
        <div class="field">
          <%= f.label :password %><br/>
          <%= f.password_field :password %><br/>
        </div>
        <div class="actions">
          <input id="session_submit" name="commit" type="submit" value="Sign in"/>
        </div>
      <% end %>
    <% else %>
      <%= current_user.name %>
       <p> Devices: </p>
       <p><%= link_to("sign out", signout_path) %></p>
    <% end %>
  </div>

  <%= yield %>
  <!-- <%= debug(params) if Rails.env.development? %> -->
  <div id="footer">
    (c) Mateos Consulting
  </div>
</div>
</body>

</html>

gtracker/app/views/main/index.html.erb
<div class="main_content">

  <div class="main_points">
    <p> <h1> Security </h1> </p>
    <ul>
      <li>Track your phone if it is stollen. </li>
      <li>Keep track of your kids location while they are out. </li>
      <li>Get notifications when they reach school, or *if* they don't. </li>
    </ul>
  </div>
  <div class="main_points">
    <p> <h1> Social </h1> </p>
    <ul>
      <li>Earn points and beat friends by covering more ground. </li>
      <li>Travel to our daily random nearby locations to earn easy bonus points. </li>
      <li>Compare your earned points against your friends. </li>
    </ul>
  </div>
  <div class="main_points">
    <p> <h1> Fitness </h1> </p>
    <ul>
      <li>Track your daily KM's and earn points for beating your last. </li>
      <li>Keep fit while having fun! </li>
    </ul>
  </div>
  <div class="main_points">
    <p><h1> Corporate </h1></p>
    <ul>
      <li>Keep track of how long your employees spend on site. </li>
      <li>Maintain accurate logs of car travel distances. </li>
    </ul>
  </div>
  <div class="main_points_button"> 
    <h1> <%= link_to("Sign up", signup_path) %> </h1>
  </div>
</div>

gtracker/app/views/shared/_error_messages.html.erb
<%if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> </h2>
    <p> fields: </p>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
<% end %>

gtracker/app/views/users/new.html.erb
<h1> Signup </h1>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  <div class="actions">
    <input id="user_submit" name="commit" type="submit" value="Sign up"/>
  </div>
<% end %>

gtracker/app/views/users/show.html.erb
<% if signed_in? %>
  <p>Name: <%= current_user.name %> </p>
  <p>Email: <%= current_user.email %></p>
<% end %>